version: '3.8'
services:
  database:
    image: postgres
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=project_database
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "project_database"]
      interval: 5s
      timeout: 30s
      retries: 6
volumes:
  database:
    driver: local